context:
  name: scorecard
  version: "5.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/ossf/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 4fbcb442071d5e463c8d20f8bc8ac52502e874e06a395887469c84335f4b21fb
    target_directory: src
  - url: https://raw.githubusercontent.com/in-toto/attestation/cf4dd91962480c5106007d3f8bfb2731e6eced4a/LICENSE
    sha256: b3a6ac899861c2c28a1abd5c7ea8733fefaed6938d730e099c42671386032aeb
    file_name: LICENSE-intoto

build:
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses --ignore github.com/in-toto/attestation
    - if: win
      then: go build -v -buildmode=pie -trimpath -modcacherw -o %LIBRARY_BIN%\scorecard.exe -ldflags="-s"
      else: go build -v -buildmode=pie -trimpath -modcacherw -o $PREFIX/bin/scorecard -ldflags="-s -w"
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script: scorecard --help

about:
  homepage: https://scorecard.dev
  summary: OpenSSF Scorecard - Security health metrics for Open Source
  description: Scorecard is an automated tool that assesses a number of important heuristics ("checks") associated with software security and assigns each check a score of 0-10.
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
    - LICENSE-intoto
  repository: https://github.com/ossf/scorecard
  documentation: https://scorecard.dev

extra:
  recipe-maintainers:
    - xhochy
